apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 3
  selector:
      matchLabels:
        app: nginx-blue
  template:
    metadata:
      labels:
        app: nginx-blue
    spec:
      containers: 
        - name: nginx-blue
          image: myacrforme.azurecr.io/blue-nginx:3
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi