apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
spec:
  replicas: 3
  selector:
      matchLabels:
        app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers: 
        - name: nginx-green
          image: myacrforme.azurecr.io/green-nginx:4
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi