apiVersion: v1
kind: Service
metadata: 
  name: production-service
  labels: 
    app: nginx-green
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: nginx-green
  type: LoadBalancer